### ISSUE TITLE
Fix SVG handling in Firefox

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame-trace#130]
Firefox doesn't load our inline SVG images if they have a hex colour `fill` property on the path. We need to figure out how to avoid this.

**Comment by smee** [comment]
The problem seems to be the `#` character. It needs to be url encoded, so a simple replace with `%23` does the trick. Doing so manually in the element inspector leads to a correct rendering of the icons.

**Comment by danielcompton** [comment]
Thanks, that's very helpful!
