### ISSUE TITLE
Occasionally wrong order of traced events when using `:dispatch`

### ISSUE THREAD

**Issue by p-himik** [Day8/re-frame-trace#131]
Suppose you have an event handler `:a` that only returns `{:dispatch [:b]}`, and some event handler `:b`.
Then, if you dispatch `:a` multiple times, the trace panel of `re-frame-trace` would sometimes change the order of `:a` and `:b`.
It happens about 1 time in 50-100, but still can be pretty confusing when it does happen.

**Comment by danielcompton** [comment]
Is this still an issue in the latest versions of re-frame-trace? Can you provide some screenshots or a minimal reproduction case?

**Comment by p-himik** [comment]
No, I couldn't reproduce it at all. Thanks!
