### ISSUE TITLE
Expanding one map in path inspector also expands other maps

### ISSUE THREAD

**Issue by p-himik** [Day8/re-frame-trace#134]
Before clicking:
![image](https://user-images.githubusercontent.com/4410314/35469869-202ced1c-0371-11e8-905e-0df4ad49dbea.png)

After clicking on the triangle to the left of `{:roman chords`:
![image](https://user-images.githubusercontent.com/4410314/35469873-377ace62-0371-11e8-9a5f-55e4a8ea4d84.png)

**Comment by danielcompton** [comment]
Thanks for the report!
