### ISSUE TITLE
reg-sub-raw subscriptions are not traced on run

### ISSUE THREAD

**Issue by zalky** [Day8/re-frame-trace#140]
It doesn't seem that reg-sub-raw subscriptions are traced when they run, even when their result clearly changes. However, they are traced on creation.

On  0.1.11 and 0.1.18.

**Comment by danielcompton** [comment]
Hmm, `reg-sub-raw` functions are run directly, whereas `reg-sub` functions are wrapped before registering with the handler. It's the wrapping point that we rely on. One option is to require the user to add the tracing macros if they want to use `reg-sub-raw`, but that isn't ideal. I'll have to think about this, and see what other options we have.

**Comment by danielcompton** [comment]
For now I think the best advice is that if you want to trace a `reg-sub-raw` subscription results, you need to add the same tracing code that we have over `reg-sub`. Note however that the tracing macros are considered internal for now and may change in future re-frame releases (though we have no plans to change it, and it hasn't changed for a year).

**Comment by zalky** [comment]
Thanks @danielcompton , not the end of the world as I am already wrapping them.
