### ISSUE TITLE
Make CSS not inline

### ISSUE THREAD

**Issue by daiyi** [Day8/re-frame-trace#24]
~~Possible solutions:~~

- ~~SASS ([plugin](https://github.com/Deraen/sass4clj#leiningen))~~
- ~~Garden~~

This is a prerequisite for #17, because the panel is currently picking up styles from its parent window, so we need to add a CSS-reset, which would be very unwieldy inline (though I suppose it's totally possible).

Edit: We will use clojure macro to read a CSS file (improving the current way, in which we are defining CSS in a string within cljs), and a separate issue is made to introduce CSS preprocessing!

**Comment by danielcompton** [comment]
Yep, those are both good options, as long as it doesn't require the user to manually add the CSS, either are probably good options. It might also be worth taking a look at what (if any?) support Google Closure provides for CSS: https://google.github.io/closure-library/api/ ?
