### ISSUE TITLE
Handle changing window viewport size when trace window is hidden

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame-trace#26]
When re-frame-trace is hidden, it is just moved to the right hand edge of the screen, so it can smoothly animate on when it is unhidden. However if you change the size of the window (say by making it wider, or removing Chrome Devtools, the tracing window stays in it's fixed position. It would be good for it to reset it's position to the right hand side of the window whenever the viewport size changes.

**Comment by saskali** [comment]
note: set min-width
