### ISSUE TITLE
Display fully qualified namespace for events in traces

### ISSUE THREAD

**Issue by saskali** [Day8/re-frame-trace#33]
- for bigger applications, it is common to have similar event names across multiple namespaces
- that makes it harder to understand where event is being dispatched
- suggestion: display fully qualified namespace for events

**Comment by danielcompton** [comment]
This would be a really good feature to add. I would suggest also looking at shortening the namespace so that it doesn't get too long and hard to read. Some Java logging libraries and IntelliJ do this: https://logback.qos.ch/manual/layouts.html#conversionWord.

**Comment by danielcompton** [comment]
Fixed in #100.
