### ISSUE TITLE
Fix CSS glitches

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame-trace#44]
I noticed this on one of our internal projects:

<img width="475" alt="screenshot of google chrome 16-08-17 5-00-05 pm" src="https://user-images.githubusercontent.com/811954/29347982-600411ca-82a4-11e7-81cb-b447005121f7.png">

**Comment by daiyi** [comment]
Ah, it seems the host project is overriding the css panel again. I'll make another pass over the panel styles

**Comment by danielcompton** [comment]
This is still a bit of an issue
<img width="606" alt="screenshot of slack 25-08-17 11-10-15 am" src="https://user-images.githubusercontent.com/811954/29692783-00aeb0ac-8986-11e7-8c47-3ac20598689c.png">

**Comment by danielcompton** [comment]
Not sure if there are some cool new CSS isolation features you can use to help with this?

**Comment by danielcompton** [comment]
@daiyi fixing this is a bit of a blocker for us to use it on our internal projects more.

**Comment by Dexterminator** [comment]
Perhaps these links are useful for fixing this?

https://developer.mozilla.org/en/docs/Web/CSS/all
https://stackoverflow.com/questions/10064172/how-to-isolate-a-div-from-public-css-styles

**Comment by danielcompton** [comment]
This is still an issue after #60.

**Comment by daiyi** [comment]
The links above are good inspiration but don't offer a complete solution, so I've been working on it a bit every day in the last week or so. The `all` selector blows away all the user-agent styles, so I've been putting them back in, and testing on a couple browsers.

**Comment by danielcompton** [comment]
What we really want I think is `all: revert author origin`, but that is not really supported yet: http://caniuse.com/#feat=css-revert-value.

**Comment by danielcompton** [comment]
This is probably the ultimate: http://caniuse.com/#feat=shadowdom
