### ISSUE TITLE
Print dispatched params for event traces

### ISSUE THREAD

**Issue by daiyi** [Day8/re-frame-trace#45]
Currently, the extra info under each trace is the metadata.

![screenshot from 2017-08-16 10-55-40](https://user-images.githubusercontent.com/1589186/29355476-751da68a-8271-11e7-8516-32c06d58f75a.png)

See above: the metadata for the `:event` trace is empty because the event doesn't have metadata!

The `:event` traces extra info should instead show the dispatched event params, because this is something that people often println to check.

**Comment by danielcompton** [comment]
Hmm, they should be there, https://github.com/Day8/re-frame/blob/v0.10.1/src/re_frame/events.cljc#L61-L63

**Comment by saskali** [comment]
closed in #50
