### ISSUE TITLE
Filter out internal traces

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame-trace#57]

**Comment by saskali** [comment]
do you mean re-frames internals like e.g. `:re-frame.router/fsm-trigger` with internal traces? does it include anything else?

**Comment by danielcompton** [comment]
That + Reagent rendering internals (if there are any, can't remember). We can update the list if we need to add more.

**Comment by danielcompton** [comment]
`:re-frame.router/fsm-trigger`, `componentwillunmount`
