### ISSUE TITLE
Fix logging data structures to console

### ISSUE THREAD

**Issue by saskali** [Day8/re-frame-trace#73]
- steps to reproduce: click on data structure to print to console
- following error occurs for all operation type details except for event details: 
**CLJS DevTools internal error: TypeError: Cannot use 'in' operator to search for 'constructor' in rx10**

**Comment by Dexterminator** [comment]
Hmm, this looks a bit familiar. Which version of cljs-devtools are you using in the host project? If I recall correctly we had a similar problem at work which went away with a devtools upgrade.

**Comment by saskali** [comment]
you're right! I just upgraded from 0.8.2 to 0.9.4 and it works now, thank you :)
