### ISSUE TITLE
Save/highlight paths into app-state 

### ISSUE THREAD

**Issue by daiyi** [Day8/re-frame-trace#81]
Allow user to specific some paths into app-state to highlight and remain expanded.

**Comment by danielcompton** [comment]
I was wondering if the paths would extract out the subset of data and just display that. It might be easier to see for deeply nested data. Not sure.

**Comment by daiyi** [comment]
That's a good point! and it would certainly be easier to implement (:

**Comment by danielcompton** [comment]
This is fixed now.
