### ISSUE TITLE
Traces render slowly after a while

### ISSUE THREAD

**Issue by Dexterminator** [Day8/re-frame-trace#91]
Since we keep appending traces to the list, the rendering becomes slow after using the application for a while. Perhaps we should keep a sliding window of traces instead of appending infinitely?

**Comment by danielcompton** [comment]
Yep, that sounds very sensible.

**Comment by danielcompton** [comment]
I've pushed a SNAPSHOT with this fixed and a few others. The rendering is still a bit rough on this, but I'll work on it some more.
