### ISSUE TITLE
Add configuration to allow people to focus in on interesting namespaces

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame-trace#95]
e.g. when rendering, drop the `re_com.*` names that come in. Similar to what exception trackers do to filter out data.

**Comment by zalky** [comment]
This would be super useful. Until this is implemented, do you think there's a simple way I could turn tracing off at the re-frame level? There's one subscription in particular that is introducing a lot of noise.

**Comment by danielcompton** [comment]
Not at the moment, we only have a "contains" filter, not the inverse. A noisy subscription _may_ indicate that it is depending on app-db unnecessarily when it should be depending on another subscription, although there are cases for it.

**Comment by zalky** [comment]
Thanks for the direction Daniel. It was a single internal subscription for the subgraph library. The library relies heavily on a single `(deref (subscribe ...))` formulation, which (while cached) introduced a lot of noise into the trace. The fn was easily replaced.

Looking forward to the new rollups! Thanks for all the hard work, re-frame-trace is a huge selling point of re-frame.

**Comment by danielcompton** [comment]
This is fixed a few versions back, you can now filter out uninteresting namespaces.

**Comment by zalky** [comment]
Yeah, I was excited to see a tonne of great new features in the last couple of releases, they look great! However, I haven't been able to get the namespaces filtering to work yet.

For example, I'm using the `day8.re-frame.async-flow-fx` library for my app boot sequence, and I tried filtering out `:async-flow/id-#` events from the trace. I've tried both the namespace of the event id, `async-flow`, as well as the namespace of the actual file the events are in `day8.re-frame.async-flow-fx` to no effect.

I've also tried filtering out my own events by both id, as well as file, to no effect. So for example, I have an event called `:document/load` in `project.events.document` ns, and neither `document`, nor `project.events.document` filters seem to filter out the event from the trace. Not sure if I'm doing something wrong.

**Comment by danielcompton** [comment]
If you'd like to filter out events, you need to use the "Ignore epochs for:" setting:

<img width="666" alt="screenshot of google chrome 10-02-18 6-59-57 pm" src="https://user-images.githubusercontent.com/811954/36059066-a65d5768-0e94-11e8-87be-0059a46f67ff.png">

Does that work?

**Comment by zalky** [comment]
Hmm, doesn't appear to:

<img width="443" alt="screen shot 2018-02-10 at 9 16 14 am" src="https://user-images.githubusercontent.com/11185842/36062909-54463d1a-0e43-11e8-8ae6-eebdcc07635b.png">
<img width="450" alt="screen shot 2018-02-10 at 9 16 27 am" src="https://user-images.githubusercontent.com/11185842/36062910-57714ce6-0e43-11e8-9d95-79d7f2073535.png">

**Comment by danielcompton** [comment]
Ah right, it should be filtering it out from the top event bar (show it doesn't show up as an epoch when you go backwards and forwards with the arrows), but the traces will still be captured in the traces panel.
