### ISSUE TITLE
Shorten namespaces to use less space

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame-trace#96]

**Comment by mhuebert** [comment]
I've written some functions for namespace-aware truncation in my fork, which may be relevant, depending on what you had in mind with this issue. Examples: https://github.com/mhuebert/re-frame-trace/blob/preview-event-params/src/day8/re_frame/trace/pretty_print_condensed.cljs#L111

I can wrap that in a PR (would be easiest after the React 16 PR is merged)

**Comment by danielcompton** [comment]
Awesome, thanks I'll take a look at that, hopefully today. If you want to open a PR that would be helpful, but I can also review it as is.
